d1max = max(self.first_derivative)
d1maxi = self.first_derivative.index(d1max)
d1min = min(self.first_derivative)
d1mini = self.first_derivative.index(d1min)

d2max = max(self.self.second_derivative[: len(self.self.second_derivative) // 2])
d2maxi = self.self.second_derivative.index(d2max, 0, len(self.self.second_derivative) // 2)
d2min = min(self.self.second_derivative[: len(self.self.second_derivative) // 2])
d2mini = self.self.second_derivative.index(d2min, 0, len(self.self.second_derivative) // 2)

d2max2 = max(self.self.second_derivative[len(self.self.second_derivative) // 2 :])
d2maxi2 = self.self.second_derivative.index(d2max2, len(self.self.second_derivative) // 2)
d2min2 = min(self.self.second_derivative[len(self.self.second_derivative) // 2 :])
d2mini2 = self.self.second_derivative.index(d2min2, len(self.self.second_derivative) // 2)

d3max = max(self.self.third_derivative[:d1maxi])
d3maxi = self.self.third_derivative.index(d3max, 0, d1maxi)
d3max2 = max(self.self.third_derivative[d1maxi : len(self.self.third_derivative) // 2])
d3maxi2 = self.self.third_derivative.index(d3max2, d1maxi, len(self.self.third_derivative) // 2)
d3max3 = max(self.self.third_derivative[len(self.self.third_derivative) // 2 :])
d3maxi3 = self.self.third_derivative.index(d3max3, len(self.self.third_derivative) // 2)
d3min = min(self.self.third_derivative[:len(self.self.third_derivative) // 2])
d3mini = self.self.third_derivative.index(d3min, 0, len(self.self.third_derivative) // 2)
d3min2 = min(self.self.third_derivative[len(self.self.third_derivative) // 2 : d1mini])
d3mini2 = self.self.third_derivative.index(d3min2, len(self.self.third_derivative) // 2, d1mini)
d3min3 = min(self.self.third_derivative[d2mini2:])
d3mini3 = self.self.third_derivative.index(d3min3, d2mini2)
