# TODO: remove \t from Profile->raw_data, and avoid those horrible "\t\tSOMETHING"...

import os
import numpy as np
import matplotlib.pyplot as plt
from tabulate import tabulate
from scipy.signal import find_peaks, medfilt
from MyUtils import *




# --- Scan ---
# stores scan data and parameters in a dictionary.

class Scan:
   # scan properties
   scan_num: int
   fields: dict
   data: list

   # calculated data
   derivative: list
   inflection_points: list

   # useful data
   profile_out_dir: str

   def __init__(self, _scan_num, _raw_data, _begin, _end, _profile_out_dir):
      self.scan_num = _scan_num
      self.fields = {}
      self.data = []
      self.derivative = []
      self.inflection_points = []
      self.profile_out_dir = _profile_out_dir

      # loop through the region, as long as "BEGIN_DATA" isn't encountered, keep collecting fields,
      # once it is encountered, collect floats
      i = _begin + 1
      while i != _end:
         # if it's a field, separate field name and value (they're separated with an equal sign), and put them in the fields dict
         if _raw_data[i].find("BEGIN_DATA") == -1:
            tokens = _raw_data[i].replace("\t", "").split("=")
            self.fields[tokens[0]] = tokens[1]
         # otherwise collect the numbers in the current line as pairs and put them in the data list
         else:
            j = i + 1
            while j != _end - 1:
               # removing empty strings (once separators) from list and cast the rest to floats
               nums = [e for e in _raw_data[j].split("\t") if e]
               self.data.append([float(nums[0]), float(nums[1])])
               j += 1
            # stop parsing
            break
         i += 1

      self.produce_results()


   # Calculate derivative, than apply median filter to portions of the derivative to
   # eliminate peaks generated by experimental errors jumps in the original data.
   # These portions are identified as external intervals of the intersections between
   # the original data curve and a third of the mean (arbitrary value... ugh).
   # Once filtered, max and min of the derivative will be the functions high and low,
   # which are the derivative values at the inflection points positions.
   # To find the positions take the index of the peak in the derivative, and use it as index for
   # both derivative function and original data
   def find_inflection_points(self):

      # calculate and locally filter the derivative
      self.derivative = calc_derivative(self.data)
      data_average = [np.mean(extract_column(self.data, 1)) / 3.0 for _ in range(len(self.data))]
      intersections = find_intersections(extract_column(self.data, 1), data_average)
      self.derivative = median_filter(self.derivative, 5, [[0,intersections[0]], [intersections[1], len(self.derivative)]])

      # find peaks/valleys and their positions
      pmax = max(self.derivative)
      pmaxi = self.derivative.index(pmax)
      pmin = min(self.derivative)
      pmini = self.derivative.index(pmin)

      pos_data = extract_column(self.data, 0)
      dose_data = extract_column(self.data, 1)

      # save inflection points data: [pos, [derivative_value, data_value]]
      self.inflection_points = [
         [pos_data[pmaxi + 1], [pmax,dose_data[pmaxi + 1]]], # positive peak
         [pos_data[pmini + 1], [pmin,dose_data[pmini + 1]]],  # negative peak
      ]

      self.inflection_points = [
         [
            (pos_data[pmaxi] + pos_data[pmaxi + 1]) / 2.0,
            [pmax, (dose_data[pmaxi] + dose_data[pmaxi + 1]) / 2.0]
         ],
         [
            (pos_data[pmini] + pos_data[pmini + 1]) / 2.0,
            [pmin, (dose_data[pmini] + dose_data[pmini + 1]) / 2.0]
         ]
      ]

      print(f"pos: {self.inflection_points[0][0] == -self.inflection_points[1][0]}, deriv: {self.inflection_points[0][1][0] == -self.inflection_points[1][1][0]}, dose: {self.inflection_points[0][1][1] == self.inflection_points[1][1][1]}, filt: {pmaxi > intersections[0]},{pmini < intersections[1]}")


   def output_plot(self):
      # build axis for plot:
      # x: positions
      # y: data, derivative, mean, inflection points
      x = extract_column(self.data[:-1], 0)
      y = self.derivative
      y2 = [np.mean(self.data) / 3.0 for _ in range(len(self.data) - 1)]
      dose_data = extract_column(self.data[:-1], 1)

      # plot components
      fig, ax = plt.subplots()
      ax.plot(x, dose_data, c = "blue")
      ax.plot(x, y, c = "red")
      ax.plot(x, y2, c = "purple")
      # HORRIFYING, plot derivative peaks and actual inflection points
      ax.scatter(
         [self.inflection_points[0][0], self.inflection_points[1][0], self.inflection_points[0][0], self.inflection_points[1][0]],
         [self.inflection_points[0][1][0], self.inflection_points[1][1][0], self.inflection_points[0][1][1], self.inflection_points[1][1][1]],
         c = "green")
      # save plot in the right profile subdirectory
      plt.savefig(f"{self.profile_out_dir}/{self.scan_num}.png")
      plt.close(fig)
      

   def produce_results(self):
      self.find_inflection_points()
      self.output_plot()




# --- Profile ---
# reads a file and extracts scan data present in that file
# by parsing scan by scan each field and collecting numerical data,
# organised in DataScans instances.

class Profile:
   name: str
   scans: list
   iso_field_size: str

   def __init__(self, file_path: str, out_dir: str):
      self.name = file_path.split("/")[-1].replace(".mcc", "")
      self.iso_field_size = self.name.split(" ")[3]
      self.scans = []
      
      raw_data = []

      print(f"{self.name}")

      # create output profile subdirectory
      # in the output directory there will be a subdir for every profile (with
      # the plot of each scan) and the inflection points table.
      profile_out_dir = f"{out_dir}/{self.name}/"
      if not os.path.exists(profile_out_dir):
         os.mkdir(profile_out_dir)

      # read file
      with open(file_path, "r") as f:
         raw_data = f.read().split("\n")
         
      # parsing
      i = 0
      end_region_index = 0
      while i < len(raw_data):
         # when a BEGIN_SCAN is found, highlight its region up to END_SCAN, and build a DataScan out of it
         if "\tBEGIN_SCAN" in raw_data[i].split(' '):
            scan_num = int(raw_data[i].split(" ")[-1])

            # OMG!!! what are we, babies?! c'mon...
            if scan_num < 10:
               end_region_index = raw_data.index(f"\tEND_SCAN  {scan_num}")
            else:
               end_region_index = raw_data.index(f"\tEND_SCAN {scan_num}")

            self.scans.append(Scan(scan_num, raw_data, i, end_region_index, profile_out_dir))

            # skip content in between
            i = end_region_index
         i += 1



# --- Cacher ---
# stores all Profiles present in a folder

class Cacher:
   profiles: list
   res_dir: str # where to find data
   out_dir: str # where to store data

   def __init__(self, _res_dir: str, _out_dir: str):
      self.profiles = []
      self.res_dir = _res_dir
      self.out_dir = _out_dir

      # create filelist
      filelist = []
      for root, dirs, files in os.walk(_res_dir):
         for _file in files:
            current_file_path = os.path.join(root,_file).replace("\\", "/")
            filelist.append(current_file_path)

      # create profile out of each file in filelist
      for f in filelist:
         self.profiles.append(Profile(f, self.out_dir))

      self.output_tables()


   def create_table(self, profiles: list):
      with open(f"{self.out_dir}/{profiles[0].name.split(' ')[-1]}.txt", "w") as f:
         table = [["depth"] + [e.name.split(" ")[3] for e in profiles]]
         for s in range(len(profiles[0].scans)):
            temp_table_row = [float(profiles[0].scans[s].fields["SCAN_DEPTH"]) / 10.0]
            for p in range(len(profiles)):
               try:
                  temp_table_row.append(abs(profiles[p].scans[s].inflection_points[0][0] / 10.0))
               except IndexError:
                  temp_table_row.append(0.0)
               except:
                  raise Exception("Something went terribly wrong...")
            table.append(temp_table_row)
         for r in table:
            for c in r:
               f.write(f"{c}\t".expandtabs(8))
            f.write("\n")

   def output_tables(self):
      # group profiles of same measurement
      measurements: dict = dict()
      for p in self.profiles:
         measurement_name = p.name.split(" ")[-1]
         if measurement_name in measurements:
            measurements[measurement_name].append(p)
         else:
            measurements[measurement_name] = [p]

      for k, v in measurements.items():
         self.create_table(v)
